<?php
session_start();
if (!isset($_SESSION['username']) || $_SESSION['role'] !== 'admin' && $_SESSION['role'] !== 'manager' && $_SESSION['role'] !== 'user') {
    header("Location: ../auth/login.php");
    exit;
}

// Include TCPDF library
require_once('../../vendor/autoload.php'); // Ganti dengan path yang sesuai

// Koneksi ke database
include '../../config/db.php'; // Ganti dengan path yang sesuai

// Buat instance TCPDF
$pdf = new TCPDF();
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('Your Name');
$pdf->SetTitle('Laporan Transaksi');
$pdf->SetSubject('Laporan Transaksi');
$pdf->SetKeywords('TCPDF, PDF, laporan, transaksi');

// Set default header data
$pdf->SetHeaderData(PDF_HEADER_LOGO, PDF_HEADER_LOGO_WIDTH, 'Laporan Transaksi', 'Generated by Inventory App');

// Set header and footer fonts
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// Set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// Set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// Set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// Set font
$pdf->SetFont('helvetica', '', 12);

// Add a page
$pdf->AddPage();

// Query untuk mengambil data transaksi
$query = "SELECT t.id, b.nama_barang, t.jenis, t.jumlah, t.tanggal 
          FROM transaksi t 
          JOIN barang b ON t.id_barang = b.id";
$result = $conn->query($query);

// Ambil tanggal dari parameter GET
$startDate = isset($_GET['start_date']) ? $_GET['start_date'] : '';
$endDate = isset($_GET['end_date']) ? $_GET['end_date'] : '';

// Query untuk mengambil data barang dengan filter tanggal
$query = "SELECT t.id, b.nama_barang, t.jenis, t.jumlah, t.tanggal 
          FROM transaksi t 
          JOIN barang b ON t.id_barang = b.id
          WHERE t.tanggal BETWEEN ? AND ?";
$stmt = $conn->prepare($query);
$stmt->bind_param("ss", $startDate, $endDate);
$stmt->execute();
$result = $stmt->get_result();


// Buat tabel untuk laporan
$html = '<h2>Laporan Transaksi</h2>';
$html .= '<table border="1" cellpadding="5">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nama Barang</th>
                    <th>Jenis</th>
                    <th>Jumlah</th>
                    <th>Tanggal</th>
                </tr>
            </thead>
            <tbody>';

if ($result->num_rows > 0) {
    while ($row = $result->fetch_assoc()) {
        $html .= '<tr>
                    <td>' . $row['id'] . '</td>
                    <td>' . $row['nama_barang'] . '</td>
                    <td>' . $row['jenis'] . '</td>
                    <td>' . $row['jumlah'] . '</td>
                    <td>' . date('d-m-Y H:i:s', strtotime($row['tanggal'])) . '</td>
                </tr>';
    }
} else {
    $html .= '<tr><td colspan="5">Tidak ada data transaksi.</td></tr>';
}

$html .= '</tbody></table>';

// Output the HTML content
$pdf->writeHTML($html, true, false, true, false, '');

// Close and output PDF document
$pdf->Output('laporan_transaksi.pdf', 'I'); // 'I' untuk menampilkan di browser, 'D' untuk download
?>